version: 2.1
jobs:
  install:
    working_directory: ~/project/blah
    docker:
      - image: vuejs/ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vue-circle-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            ls -al
            yarn install
            ls -al
      - save_cache:
          key: v1-vue-circle-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/
          paths:
            - project/blah
  lint:
    working_directory: ~/project/blah
    docker:
      - image: vuejs/ci
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint Code
          command: |
            ls -al
            yarn lint

workflows:
  version: 2
  install_and_lint:
    jobs:
      - install
      - lint:
          requires:
            - install