version: 2.1

jobs:
  install:
    docker:
    - image: vuejs/ci
    steps:
      - run:
            name: Install dependencies
            command: yarn install
  lint:
    docker:
    - image: vuejs/ci
    steps:
      - run:
            name: Lint code
            command: yarn lint
  test:
    docker:
    - image: vuejs/ci
    steps:
      - run:
            name: Run unit tests
            command: yarn test:unit

workflows:
 version: 2
 lint_and_test:
   jobs:
     - install
     - lint:
         requires:
           - install
     - test:
         requires:
           - install
