version: 2.1
jobs:
  install:
    working_directory: ~/project/blah
    docker:
      - image: vuejs/ci
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            ls -al
            yarn install
            ls -al
      - persist_to_workspace:
          root: ~/
          paths:
            - project/blah
  lint:
    working_directory: ~/project/blah
    docker:
      - image: vuejs/ci
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint Code
          command: |
            ls -al
            yarn lint

workflows:
  version: 2
  install_and_lint:
    jobs:
      - install
      - lint:
          requires:
            - install