version: 2.1
jobs:
  install:
    working_directory: ~/project
    docker:
      - image: vuejs/ci
    steps:
      - run:
          name: Install dependencies
          command: |
            ls -al
            yarn install
  lint:
    working_directory: ~/project
    docker:
      - image: vuejs/ci
    steps:
      - checkout
      - run:
          name: Lint Code
          command: |
            ls -al
            yarn lint

workflows:
  version: 2
  install_and_lint:
    jobs:
      - install
      - lint:
          requires:
            - install