version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

defaults: &defaults
  working_directory: ~/project/spike
  docker:
    - image: vuejs/ci

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-test-vue-circle-ci-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            ls -al
            yarn install --frozen-lockfile
            ls -al
      - save_cache:
          key: v1-test-vue-circle-ci-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/
          paths:
            - project/spike
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint Code
          command: |
            ls -al
            yarn lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Unit testing
          command: |
            yarn test:unit --coverage
      - codecov/upload:
          file: coverage/*.json
      - store_artifacts:
          path: coverage
      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: yarn test:unit --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run: ls -al
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit


workflows:
  version: 2
  install_and_lint:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
