version: 2.1
jobs:
  install:
    working_directory: ~/project/blah
    docker:
      - image: vuejs/ci
    steps:
      - checkout
      - run:
          name: ls
          command: |
            ls -al
      - restore_cache:
          keys:
            - v1-test-vue-circle-ci-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            ls -al
            yarn install --frozen-lockfile
            ls -al
      - save_cache:
          key: v1-test-vue-circle-ci-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/
          paths:
            - project/blah

  lint:
    working_directory: ~/project/blah
    docker:
      - image: vuejs/ci
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint Code
          command: |
            ls -al
            yarn lint
  test:
    working_directory: ~/project/blah
    docker:
      - image: vuejs/ci
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Unit testing
            ls -al
          command: |
            yarn test:unit

workflows:
  version: 2
  install_and_lint:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install